kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs2
  annotations:
    volume.beta.kubernetes.io/storage-class: "storage-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

